### ISSUE TITLE
[Req] Non-Scrolling Image Changing

### ISSUE THREAD

**Issue by Nikey646** [cocuh/intellij-wallpaper#1]
I know that you have stated in the readme that if you want "_scrolling_" images, you should use the BackgroundChibiChara plugin, however i don't want _scrolling_, i want a nice static image like what your addon provides.

I personally use [ClaudiaIDE](https://visualstudiogallery.msdn.microsoft.com/9ba50f8d-f30c-4e33-ab19-bfd9f56eb817) when developing in Visual Studio, and it offers a nice simple "slideshow" feature, that just fades the current image out and fades a new one in.

I would love it if you could add this to your current plugin, since it is such a simple, yet nice feature, that gives you variety in your backgrounds if you want it. Plus all the images i use in Visual Studio I have chosen to use, perfectly sit in the bottom right corner with any clipped parts of the image appearing as if they are poking into the text editing area.

Edit: Also, what is the image you are using in your example screenshot? :D

**Comment by cocuh** [comment]
Thank you for suggesting feature.

I tried slideshow before, and I learned that animation is hard because of intellij-platform implementation. Currently, wallpaper feature is hard-coded to load from file or url in intellij-platform. So, what plugin can do is only applying the filepath or url to APIs.
Slideshow without animation is possible, but terrible. I want fade-in/out slideshow. I sent some requests to intellij team to extend the wallpaper APIs. I'm waiting the response.

P.S. The anime title of screenshot is `prisma illya`, google `prisma illya wallpaper`. :blush:

**Comment by Nikey646** [comment]
Hmm, that is annoying.

Do you think that you could make a release on github only that allows for a slideshow for now, without fading, until you get a response from the Intellj team, who will hopefully extend the Walpaper API. While the fade would be nice, and it would look very jagged for the images to randomly change, I believe it's still a feature i would personally use.

Thank you for the image :>

**Comment by cocuh** [comment]
I don't think release slideshow feature for now, currently.
Slideshow will require to modify SettingUI and SaveDataModel, and to implement periodical Scheduler. It's hard work. Furthermore, if API are extended in the future, more modification may be required. I want to decide it after jetbrains team response, sorry.
Whether they decline or accept, I want to add the slideshow feature, even if fading is not possible.

**Comment by Nikey646** [comment]
Alright, no problem. I didn't realize it would be a fair amount of effort to add it, and even more to modify it later if API is extended.

I can wait until you get a response from the Intellij/Jetbrains team. Thank you for your response and considerations!

**Comment by progsmile** [comment]
+1) That will be great feature)
not slideshow I think, just changing ordered or random backgrounds in some interval)
I think it's possible, because of javascript console, but I also  dunno details
So, please man))))

**Comment by aolphn** [comment]
My android studio can't launch after I install your plugin.There is error message as following:
Plugin 'org.typowriter.intellij.plugins.wallpaper' failed to initialize and will be disabled.  Please restart Android Studio.

com.intellij.diagnostic.PluginException: org/typowriter/intellij/plugins/wallpaper/WallpaperApplicationComponent : Unsupported major.minor version 52.0 [Plugin: org.typowriter.intellij.plugins.wallpaper]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:278)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:408)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:455)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:447)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:197)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
    at java.awt.EventQueue.access$300(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:706)
    at java.awt.EventQueue$3.run(EventQueue.java:704)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Caused by: java.lang.UnsupportedClassVersionError: org/typowriter/intellij/plugins/wallpaper/WallpaperApplicationComponent : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
    ... 26 more

PS:My Android studio version is 2.1.1.

**Comment by Nikey646** [comment]
@zhangkehu What does your issue have in relationship to mine? Please create a new issue on the github repo that is reporting the details and not throw it into a Request issue.

**Comment by aolphn** [comment]
@Nikey646 😱😱😱sorry
